### ISSUE TITLE
No DualBinFrontRear

### ISSUE THREAD

**Issue by Max-Fu** [ZXP-S-works/SE2-equivariant-grasp-learning#1]
Hi,

Thanks for the great work! I want to try out the simulated environments that you use in your work, but I am not able to find it, other than the reference: 
`from src.envs.dual_bin_front_rear import DualBinFrontRear`
Can you point me to where this environment can be found? 

Thanks, 
Max

**Comment by ZXP-S-works** [comment]
Hi Max-Fu,

Thanks for your interest! To run the simulated environments, please clone and install the environment repo. After that, you can run python3 ./scripts/main.py  for the simulation trianing. The DualBinFrontRear env is for the physical robot, which is not yet open-sourced.

Best,
XPZ

**Comment by Max-Fu** [comment]
Thanks so much for the help!

**Comment by SageRobots** [comment]
Do you have plans to make the DualBinFrontRear environment open source anytime soon? I was hoping to run this on a UR5 with Robotiq gripper this month.
